### ISSUE TITLE
合計の数値が合わない

### ISSUE THREAD

**Issue by Tomohiro** [occ-corp/redmine_custom_field_aggregator#2]
以下のように，日ごとの数値と，月の合計値が合わなくなっています。

![7t70ukvaa9qwsgz737cwxciph](https://cloud.githubusercontent.com/assets/54254/10502799/b2e0ab0a-732a-11e5-9521-fe1d37560862.png)

**Comment by yono** [comment]
報告ありがとうございます。

## 調べた結果

* 合計を出す場合のロジックと日毎の値を出す場合のロジックが異なっている
* 合計を出す場合は時間記録の日付のみを見ている
* 日毎の値を出す場合はチケットの日付（開始日）も見ている
* チケットの日付と時間記録の日付が異なる（月がずれている）場合に、合計値が合わなくなる

### 合計を出す場合

https://github.com/occ-corp/redmine_custom_field_aggregator/blob/d688379386345accbee7118a483b51c4a1358a73/app/models/aggregator.rb#L42-L59

* 時間記録を日付で絞り込む
* 合計する

### 日毎の値を出す場合

https://github.com/occ-corp/redmine_custom_field_aggregator/blob/d688379386345accbee7118a483b51c4a1358a73/app/models/aggregator.rb#L11-L40

* 時間記録を日付で絞り込む
* 時間記録に紐付いたチケットの開始日付を見て、該当の期間外の場合は処理対象外とする
* 日毎に合計する

## そんでどうするの

* ロジックをどちらかに統一すれば良い
* どちらに統一するかは考え中

**Comment by Tomohiro** [comment]
「時間記録」情報を「カスタムフィールド」別に集計するのがこのプラグインの存在意義(合ってる？:sweat_smile:)だとすると，「時間記録」を中心とした計算方法に寄せたほうが良いのかなー？という気がしています。

**Comment by Tomohiro** [comment]
あ，言いたいのはチケットではなく時間記録の日付中心で良いのでは？ということです。

**Comment by yono** [comment]
そうですね、時間記録の日付を使うように修正しようと思います。

**Comment by Tomohiro** [comment]
:+1:

**Comment by yono** [comment]
@Tomohiro 
GH-3 で修正できたのでこちらもクローズしますね。
